services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatapp
      MONGO_INITDB_ROOT_PASSWORD: theworldisavampire

  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chatapp
      ME_CONFIG_MONGODB_ADMINPASSWORD: theworldisavampire
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongodb_data:
